variables:
  OPENNEBULA_ENDPOINT: "http://localhost:2633/RPC2"
  OPENNEBULA_USERNAME: "oneadmin"
  OPENNEBULA_PASSWORD: "opennebula"
  OPENNEBULA_FLOW_ENDPOINT: "http://localhost:2474"
  TF_ACC: 1
  GO_VER: "1.18.2"
  DEBIAN_FRONTEND: noninteractive

stages:
  - test

test-5_12:
  stage: test
  tags:
    - amd64
#  name: "Test OpenNebula 5.12"
  image: ubuntu:20.04
  script:
    - |
      echo "updating repo and installing ci script dependencies"
      sudo apt update && sudo apt install -y curl sudo gpg tzdata
      echo "setting up opennebula apt repo"
      curl -sSfL https://downloads.opennebula.io/repo/repo.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/opennebula-archive-keyring.gpg
      sudo echo "deb [signed-by=/usr/share/keyrings/opennebula-archive-keyring.gpg] https://downloads.opennebula.io/repo/5.12/Ubuntu/20.04 stable opennebula" > /etc/apt/sources.list.d/opennebula.list
      echo "installing opennebula (this takes several minutes)"
      sudo apt-get -y update && sudo apt-get install -y opennebula opennebula-flow systemd
      echo "running oned.sh..."
      sudo source .github/scripts/oned.sh
      ls -lap
      echo "go install..."
      curl -sSfL https://dl.google.com/go/go${GO_VER}.linux-amd64.tar.gz | sudo tar -C /usr/local -xzf -
      go install
      #go test $(go list ./... | grep -v 'vendor') -v
