variables:
  OPENNEBULA_ENDPOINT: "http://localhost:2633/RPC2"
  OPENNEBULA_USERNAME: "oneadmin"
  OPENNEBULA_PASSWORD: "opennebula"
  OPENNEBULA_FLOW_ENDPOINT: "http://localhost:2474"
  TF_ACC: 1
  GO_VER: "1.18.2"

stages:
  - test

test-5_12:
  stage: test
  tags:
    - amd64
#  name: "Test OpenNebula 5.12"
  image: ubuntu:20.04
  script:
    - |
      apt update && apt install -y curl
      curl -sSfL https://dl.google.com/go/go${GO_VER}.linux-amd64.tar.gz | tar -C /usr/local -xzf -
      /usr/local/go/bin/go version
      curl -sSfL https://downloads.opennebula.io/repo/repo.key > /usr/share/keyrings/opennebula.key
      echo "deb https://downloads.opennebula.io/repo/5.12/Ubuntu/20.04 stable opennebula" > /etc/apt/sources.list.d/opennebula.list
      apt update && apt install -y opennebula opennebula-flow
      ls -lap
